FROM node:20-slim
WORKDIR /srv/ui
COPY ../.. .
RUN npm install --global pnpm && \
    pnpm install --filter studio-ui...
EXPOSE 6711
CMD ["pnpm", "--filter", "studio-ui", "dev", "--", "--host", "0.0.0.0", "--port", "6711"]
